---
# vars file for test

vulnerable_packages:
  - postfix
  - kernel-devel
  - kernel-headers
  - kernelå
  - runc
  - containerd
  - python-devel
  - python-libs
  - python
  - sudo
  - cpio
  - nss
  - nss-tools
  - nss-sysinit
  - nerdctl
  - glib2
  - less
  - microcode_ctl
  - ncurses-libs #mediums
  - ncurses
  - ncurses-base
  - dbus
  - dbus-libs
  - openssh-clients
  - openssh
  - openssh-server
  - libcurl
  - curl
  - python-urllib3
  - zlib
  - zlib-devel
  - vim-data
  - vim-minimal
  - python3-pip
  - python3-libs
  - python3
  - openssl-libs
  - openssl
  - krb5-libs
  - python-jinja2
  - libxml2
  - libxml2-python
  - python-jwcrypto