pipeline {
    options {
        timestamps()
        skipDefaultCheckout()
    }
    agent { label 'ansible' }
    parameters {
        choice(name: 'Action', choices: 'plan\napply', description: 'Manual build stages')
        string(name: 'hosts', defaultValue: 'hosts/aws_ec2.yml', description: 'Here we are providing host value')
        string(name: 'source_host', defaultValue: 'source_host=servers', description: 'Here we are providing source_host value')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Establish ssh connection') {
            steps {
                sh "aws ec2-instance-connect send-ssh-public-key --instance-id i-0f3a063e6952700ad --instance-os-user ssm-user --ssh-public-key file://~/.ssh/id_rsa.pub --profile trainee"
            }
        }
        stage('Run ansible playbook') {
            when {
                expression {
                    params.Action == 'apply'
                }
            }
            steps {
                ansiColor('xterm') {
                    sh 'cd dynamic-inventory; ansible-playbook -i $hosts -e $source_host --user ssm-user role.yml'
                }
            }
        }
    }
    post {
        always {
            echo "Clean up the workspace in deploy node!"
            cleanWs()
        }
    }
}
