---
# - name: Remove lock from specific packages
#   become: yes
#   community.general.yum_versionlock:
#     state: absent
#     name: "{{ item }}"
#   loop:
#     - kernel-devel
#     - kernel-headers
#     - kernel
#     - runc
#     - containerd
#   when: ansible_distribution == 'Amazon'

# - name: Enable kernel version 5.15
#   become: yes
#   shell: amazon-linux-extras enable kernel-5.15

- name: Upgrade list of packages on CentOS/RHEL/Amazon Linux servers
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - postfix
    - kernel-devel
    - kernel-headers
    - kernel
    - runc
    - containerd
    - python-devel
    - python-libs
    - python
    - sudo
    - cpio
    - nss
    - nss-tools
    - nss-sysinit
    - nerdctl
    - glib2
    - less
    - microcode_ctl
  ignore_errors: yes
  when: ansible_distribution == 'Amazon'