---
- name: Upgrade list of packages on Amazon Linux servers
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ affected_packages }}"
  ignore_errors: yes
  # when: ansible_distribution == 'Amazon'