---
- name: Upgrade list of packages on Amazon Linux servers
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ affected_packages }}"
  ignore_errors: yes
  when: ansible_distribution == 'Amazon'

# - name: Update cache 
#   become: yes
#   apt:
#     update_cache: yes
#   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: Upgrade list of packages on Ubuntu servers
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ affected_packages }}"
  ignore_errors: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'