---
# - name: Ensure EPEL repository is enabled
#   become: yes
#   yum_repository:
#     name: epel
#     description: Extra Packages for Enterprise Linux (EPEL)
#     file: epel.repo
#     baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#     gpgcheck: yes
#     gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
#     enabled: yes
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'

# - name: install epel-release package
#   yum: name=epel-release state=present
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'

- name: Upgrade list of packages on CentOS/RHEL/Amazon Linux servers
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - postfix
    - kernel-devel
    - kernel-headers
    - kernel
    - runc
    - containerd
    - python-devel
    - python-libs
    - python
    - sudo
  ignore_errors: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'

# - name: Update cache 
#   become: yes
#   apt:
#     update_cache: yes
#   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# - name: Upgrade all packages on ubuntu servers
#   become: yes
#   apt:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - openssh-clients
#     - openssh
#     - openssh-server
#     - python
#     - python-libs
#     - amazon-ssm-agent
#     - openssl-libs #CentOS
#     - openssl 
#     - systemd #CentOS
#     - systemd-libs #CentOS
#     - systemd-sysv #CentOS
#     - mod_ssl #CentOS
#     - httpd-tools #CentOS
#     - httpd #CentOS
#     - zlib #CentOS 
#     - nss #CentOS
#     - nss-sysinit #CentOS
#     - nss-tools #CentOS
#     - libX11-common #CentOS
#     - libX11 #CentOS
#     - libwebp-devel #Linux
#     - libwebp #Linux
#     - libssh2 #Linux
#     - libpython3.6 #ubuntu
#     - python3.6 #ubuntu
#     - python2.7 #ubuntu
#     - libpython2.7 #ubuntu
#     - kernel-devel #linux
#     - kernel-headers #linux
#     - kernel #linux
#   ignore_errors: yes
#   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 